export { default as TableOfProducts } from './TableOfProducts'
export { default as AddProductModal } from './AddProductModal'
export { default as DeleteProductModal } from './DeleteProductModal'
export { default as TableOfBrands } from './TableOfBrands'
export { default as UpdateProductModal } from './UpdateProductModal'
export { default as FilterProduct } from './FilterProduct'