export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Product } from './Product'
export { default as Warehouse } from './Warehouse'
export { default as Order } from './Order'
export { default as OrderDetail } from './OrderDetail'
export { default as Sales } from './Sales'