export { default as TableOfGoodsReceivedNotes } from './TableOfGoodsReceivedNotes'
export { default as AddGoodsReceivedNoteModal } from './AddGoodsReceivedNoteModal'
export { default as TableOfSuppliers } from './TableOfSuppliers'
export { default as AddSupplierModal } from './AddSupplierModal'
export { default as UpdateSupplierModal } from './UpdateSupplierModal'
export { default as DeleteSupplierModal } from './DeleteSupplierModal'